import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Music Player!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Song title &rarr;</h2>
            <p>Content</p>

            <div className={styles.controlPanel}>
              <button>Previous</button>
              <button>Play</button>
              <button>Next</button>
            </div>
          </div>
        </div>
      </main>
    </div >
  )
}

export default Home
